# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Generate a Project Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 10.23.0
        uses: actions/setup-node@v1
        with:
          node-version: '10.23.0'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile --silent

      - name: Build     
        run: yarn build

      - name: Run Unit Tests
        run: yarn test

      - name: Generate a Release with semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn release
